[package]
name = "Thorium"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.6"
reqwest = { version = "0.12.7" ,features = ["blocking"]}
tokio = "1.40.0"
base64 = "0.22.1"
sysinfo = "0.31.4"